### ISSUE TITLE
Error with Istio and custom namespaces with mTLS enabled

### ISSUE THREAD

**Issue by hugocortes** [openfaas/faas-netes#504]
## Expected Behaviour
OpenFaaS should work when being installed on a namespace other than `openfaas` with a function namespace other than `openfaas-fn` when Istio mTLS is enabled in cluster.
 
## Current Behaviour
When using an OpenFaaS namespace other than `openfaas` and a function namespace other than `openfaas-fn`, faas-idler, gateway, and queue worker remain at `CrashLoopBackOff` state.

Resulting behavior is similar as described in #369.

faas-idler logs:
```
panic: invalid character 'o' in literal null (expecting 'u')

goroutine 1 [running]:
main.main()
	/go/src/github.com/openfaas-incubator/faas-idler/main.go:73 +0x7e1
```

gateway logs:
```
2019/09/09 17:12:14 HTTP Read Timeout: 1m5s
2019/09/09 17:12:14 HTTP Write Timeout: 1m5s
2019/09/09 17:12:14 Binding to external function provider: http://127.0.0.1:8081/
2019/09/09 17:12:14 Async enabled: Using NATS Streaming.
2019/09/09 17:12:14 Opening connection to nats://nats.openfaas-system.svc.cluster.local:4222
2019/09/09 17:12:14 Connect: nats://nats.openfaas-system.svc.cluster.local:4222
2019/09/09 17:12:14 EOF
```

queue-worker logs
```
Loading basic authentication credentials
Connect: nats://nats.openfaas-system.svc.cluster.local:4222
can't connect to nats://nats.openfaas-system.svc.cluster.local:4222: EOF
panic: can't connect to nats://nats.openfaas-system.svc.cluster.local:4222: EOF

goroutine 1 [running]:
log.Panic(0xc00003fe08, 0x1, 0x1)
	/usr/local/go/src/log/log.go:326 +0xc0
main.main()
	/go/src/github.com/openfaas/nats-queue-worker/main.go:220 +0x458
```

## Possible Solution
When creating an Istio `DestinationRule`, it should use a host value dependent on the target namespaces.

## Steps to Reproduce (for bugs)
1. Install Istio with mTLS enabled.
2. Install OpenFaaS in a namespace other than `openfaas` and a function namespace other than `openfaas-fn`.
3. kubectl get po -n <namespace used> --watch

## Context
I was trying to install OpenFaaS using namespace: `openfaas-system` with mTLS enabled.

## Your Environment
Kubernetes on bare metal cluster. Istio v1.2.3

* What version and distriubtion of Kubernetes are you using? `kubectl version`
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-19T22:12:47Z", GoVersion:"go1.12.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

* What network driver are you using and what CIDR? i.e. Weave net / Flannel
Flannel

**Comment by sfxworks** [comment]
Hi,

I am experiencing the same issue except with the default namespaces. It appears the `--set istio.mtls=true` option doesn't work at all. 

```
ubuntu@master-1:~/openfass-v2$ kubectl get pods -n openfaas --watch
NAME                                READY   STATUS             RESTARTS   AGE
alertmanager-8447d569c8-bs5mr       1/2     Running            5          3m26s
basic-auth-plugin-76899dc95-fmxng   1/2     Running            5          3m26s
faas-idler-86b55ffcbf-h9mhk         1/2     CrashLoopBackOff   5          3m26s
gateway-598497c4fb-qq9s4            2/3     CrashLoopBackOff   5          3m25s
nats-6b6d549b56-ttzw6               1/1     Running            0          3m25s
prometheus-7f694ddc48-dxzwd         1/2     Running            5          3m25s
queue-worker-554946dc65-5kbwc       2/2     Running            2          3m25s
```

Example from idler:

```
ubuntu@master-1:~/openfass-v2$ kubectl logs -f -n openfaas faas-idler-86b55ffcbf-h9mhk -c faas-idler
panic: invalid character 'o' in literal null (expecting 'u')

goroutine 1 [running]:
main.main()
        /go/src/github.com/openfaas-incubator/faas-idler/main.go:73 +0x7e1
```

Version:
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by alexellis** [comment]
So the only problem is the idler and everything else works fine?

**Comment by alexellis** [comment]
We are going to need you to raise your own separate issue. @stefanprodan maintains the Istio support.

**Comment by alexellis** [comment]
Give detailed instructions on how to reproduce the issue including any commands you use to install Istio.
