### ISSUE TITLE
CrashLoopBackoff with Istio and mTLS enabled

### ISSUE THREAD

**Issue by sfxworks** [openfaas/faas-netes#545]
Possibly relates to https://github.com/openfaas/faas-netes/issues/504

With the latest versions and fresh install of istio, faas and k8s, I cannot get openfaas to work with the `--set istio.mtls=true` tag.

## Expected Behaviour
```
helm repo update \
 && helm upgrade openfaas --install openfaas/openfaas \
    --namespace openfaas  \
    --set basic_auth=true \
    --set functionNamespace=openfaas-fn \
    --set serviceType=ClusterIP \
    --set istio.mtls=true 
```
Yields a working deployment

## Current Behaviour
It does not.

```
ubuntu@master-1:~/openfass-v2$ kubectl get pods -n openfaas
NAME                                READY   STATUS             RESTARTS   AGE
alertmanager-8447d569c8-bs5mr       1/2     CrashLoopBackOff   25         66m
basic-auth-plugin-76899dc95-fmxng   1/2     CrashLoopBackOff   25         66m
faas-idler-86b55ffcbf-h9mhk         1/2     CrashLoopBackOff   17         66m
gateway-598497c4fb-qq9s4            2/3     Running            25         66m
nats-6b6d549b56-ttzw6               1/1     Running            0          66m
prometheus-7f694ddc48-dxzwd         1/2     CrashLoopBackOff   25         66m
queue-worker-554946dc65-5kbwc       2/2     Running            2          66m

```

**AlertManager/Basic-Auth/prometheus**: Readyness Probe failure/sigterm
```
  Warning  Unhealthy  22m (x103 over 66m)    kubelet, worker-1  (combined from similar events): Readiness probe failed: Get http://192.168.2.205:9093/-/ready: read tcp 192.168.2.35:58916->192.168.2.205:9093: read: connection reset by peer
```

Example from AlertManager (Similar to others/all recieve sigterm and gracefully exit): 
```
level=info ts=2019-11-10T09:05:59.034Z caller=main.go:429 msg=Listening address=:9093
level=info ts=2019-11-10T09:06:26.666Z caller=main.go:468 msg="Received SIGTERM, exiting gracefully..."
```

**gateway**: Similar. 
Liveness probe failures + connection refusal
```
Liveness probe failed: Get http://192.168.2.94:8080/healthz: read tcp 192.168.2.35:51868->192.168.2.94:8080: read: conn
```

`-c gateway`
```
2019/11/10 09:34:00 HTTP Read Timeout: 1m5s
2019/11/10 09:34:00 HTTP Write Timeout: 1m5s
2019/11/10 09:34:00 Binding to external function provider: http://127.0.0.1:8081/
2019/11/10 09:34:00 Async enabled: Using NATS Streaming.
2019/11/10 09:34:00 Opening connection to nats://nats.openfaas.svc.cluster.local:4222
2019/11/10 09:34:00 Connect: nats://nats.openfaas.svc.cluster.local:4222
```

`-c faas-netes`
```
ubuntu@master-1:~/test$ kubectl logs -f -n openfaas gateway-598497c4fb-qq9s4 faas-netes
2019/11/10 08:03:24 HTTP Read Timeout: 1m0s
2019/11/10 08:03:24 HTTP Write Timeout: 1m0s
2019/11/10 08:03:24 HTTPProbe: true
2019/11/10 08:03:24 SetNonRootUser: false
E1110 08:03:24.241096       1 reflector.go:134] k8s.io/client-go/informers/factory.go:131: Failed to list *v1.Endpoints: Get https://10.96.0.1:443/api/v1/namespaces/openfaas-fn/endpoints?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
E1110 08:03:25.255657       1 reflector.go:134] k8s.io/client-go/informers/factory.go:131: Failed to list *v1.Endpoints: Get https://10.96.0.1:443/api/v1/namespaces/openfaas-fn/endpoints?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
```

**faas-idler**: goroutine err
```
panic: invalid character 'o' in literal null (expecting 'u')

goroutine 1 [running]:
main.main()
        /go/src/github.com/openfaas-incubator/faas-idler/main.go:73 +0x7e1
```

**queue-worker/nats**: 
OK

## Possible Solution
https://istio.io/docs/ops/app-health-check/
May be related to healthchecks in istio + mTLS. 
Adding  `sidecar.istio.io/rewriteAppHTTPProbers: "true"` to deployments may fix this. Tested out their demo (with slight modifications to apiVersion + added selector) and all went well.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: liveness-http
spec:
  selector:
    matchLabels:
      app: liveness-http
  template:
    metadata:
      labels:
        app: liveness-http
        version: v1
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      containers:
      - name: liveness-http
        image: docker.io/istio/health:example
        ports:
        - containerPort: 8001
        livenessProbe:
          httpGet:
            path: /foo
            port: 8001
          initialDelaySeconds: 5
          periodSeconds: 5
```

## Steps to Reproduce (for bugs)

Install k8s v1.16.2 + cilium.

Install istio cni (using a different namespace for istio itself here, dont know if that is also a factor)
```
helm template deployments/kubernetes/install/helm/istio-cni --name=istio-cni --namespace=kube-system \
    --set logLevel=info \
    --set excludeNamespaces={"istio-sys2,kube-system"} | kubectl apply -f -
``` 

Install istio (tested with lb, but setting nodeport here for convenience/also happens with nodeport)
```
helm template install/kubernetes/helm/istio --name istio --namespace istio-sys2 \
    --set istio_cni.enabled=true --set certmanager.enabled=true --set gateways.istio-ingressgateway.type=NodePort --set grafana.enabled=true --set tracing.enabled=true --set global.mtls.enabled=true --set kiali.enabled=true --set certmanager.email=example@example.com --set gateways.istio-ingressgateway.sds.enabled=true --set global.k8sIngress.enabled=true --set global.k8sIngress.enableHttps=true --set global.k8sIngress.gatewayName=ingressgateway | kubectl apply -f -

```

Install faas with istio mtls enabled
```
helm repo update \
 && helm upgrade openfaas --install openfaas/openfaas \
    --namespace openfaas  \
    --set basic_auth=true \
    --set functionNamespace=openfaas-fn \
    --set serviceType=ClusterIP \
    --set istio.mtls=true 
```

## Your Environment

```
containerd --version
containerd github.com/containerd/containerd v1.3.0 36cf5b690dcc00ff0f34ff7799209050c3d0c59a
```
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

```
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic
```

```
Cilium 1.6
```

**Comment by sfxworks** [comment]
A quick test on that yielded success:
Adding the annotation `sidecar.istio.io/rewriteAppHTTPProbers: "true"` yeilded success. 
```
ubuntu@master-1:~/test$ kubectl get pods -n openfaas
NAME                                 READY   STATUS    RESTARTS   AGE
alertmanager-74c8f59f98-snzld        2/2     Running   0          67s
basic-auth-plugin-65f5d97cb7-68q2m   2/2     Running   0          67s
faas-idler-bf7bff4df-frnbs           2/2     Running   3          67s
gateway-67f687bfdd-5v5nf             3/3     Running   2          67s
nats-6b6d549b56-4sd8j                1/1     Running   0          67s
prometheus-5bc4fdd976-kl68s          2/2     Running   0          67s
queue-worker-554946dc65-26r9l        2/2     Running   1          67s
```

https://istio.io/docs/reference/config/installation-options/#sidecarinjectorwebhook-options
It may be worth noting that this is an option for istio's helm installation for others too. I didn't enable it by default as I was unsure how flux would handle it at first/how it exactly worked.

**Comment by stefanprodan** [comment]
Please see the chart readme for installing OF with Istio mTLS https://github.com/openfaas/faas-netes/blob/master/chart/openfaas/README.md#istio-mtls

**Comment by sfxworks** [comment]
Ah sorry about that
I didn't see the reference to disable healthChecks

**Comment by stefanprodan** [comment]
The health checks are not disabled but switched from http mode to exec. Using the annotations would make the probes use less CPU but would make Pilot a major single point of failure since for each check would do a roundtrip kubelet -> pilot -> pod.

**Comment by alexellis** [comment]
Thank you @stefanprodan for a very prompt response.

@sfxworks would you be interested in contributing an Istio installer command to k3sup? https://github.com/alexellis/k3sup

It uses tillerless-helm and perhaps it could be used for a short tutorial on OpenFaaS and Istio.https://docs.openfaas.com/deployment/kubernetes/#a-deploy-with-k3sup-fastest-option

**Comment by sfxworks** [comment]
@alexellis I may for another cluster. Unfortunentallly, I am working with an openstack + CPO at this time so I may need more than what k3s provides. I will see about doing a PR for this project though as I like the idea! I have been looking for a tool where I can just run a command and orchestrate setup along with init and join.
