### ISSUE TITLE
gateway/queworker and faas-idler won't start

### ISSUE THREAD

**Issue by pixeldrew** [openfaas/faas-netes#642]
## My actions before raising this issue
- [x] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

Installed k3os 0.10.1 onto VirtualVox VM from liveCD
Used https://bit.ly/2WYRmqo as starting configuration (k3os by default uses traefik as ingress lb)
Used Arkade to install openfaas

## Expected Behaviour

Gateway/Queue and FAAS-idler should start

## Current Behaviour

Gateway/Queue and FAAS-idler does not start

## Steps to Reproduce (for bugs)

1. Run k3os live CD from 
2. Install k3os to virtual disk
3. Copy kubeconfig to host:
```sh
scp rancher@10.137.0.183:/etc/rancher/k3s/k3s.yaml ./k3s-vm-config.yaml
export KUBECONFIG=`pwd`/k3s-vm-config.yaml
```
3. Use arkade to install openfaas

## Context

Trying to test out single node cluster with openfaas installed locally, i'm trying to determine if this is a viable alternative to azure-functions

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
 version: 0.12.4
* Docker version `docker version` (e.g. Docker 17.0.05 ):
containerd
* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Kubernetes
```
NAME        STATUS   ROLES    AGE   VERSION        INTERNAL-IP    EXTERNAL-IP   OS-IMAGE       KERNEL-VERSION     CONTAINER-RUNTIME
k3os-6139   Ready    master   22m   v1.17.5+k3s1   10.137.0.183   <none>        k3OS v0.10.1   5.0.0-43-generic   containerd://1.3.3-k3s2
```
* Operating System and version (e.g. Linux, Windows, MacOS):
k3os 0.10.1
* Code example or link to GitHub repo or gist to reproduce problem:

* Other diagnostic information / logs from [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting)
```
kubectl -n openfaas get deployments -l "release=openfaas, app=openfaas"
NAME                READY   UP-TO-DATE   AVAILABLE   AGE
nats                1/1     1            1           25m
basic-auth-plugin   1/1     1            1           25m
alertmanager        1/1     1            1           25m
prometheus          1/1     1            1           25m
queue-worker        0/1     1            0           25m
gateway             0/1     1            0           25m
faas-idler          0/1     1            0           25m
```

```
kubectl logs queue-worker-54cfc7d5bc-xpvq4 -n openfaas         
Loading basic authentication credentials
Connect: nats://nats.openfaas.svc.cluster.local:4222
can't connect to nats://nats.openfaas.svc.cluster.local:4222: nats: no servers available for connection
panic: can't connect to nats://nats.openfaas.svc.cluster.local:4222: nats: no servers available for connection

goroutine 1 [running]:
log.Panic(0xc0000f1da8, 0x1, 0x1)
	/usr/local/go/src/log/log.go:338 +0xac
main.main()
	/go/src/github.com/openfaas/nats-queue-worker/main.go:208 +0x5ac
```

```
kubectl logs faas-idler-d4dd46745-8xmtq -n openfaas                  
panic: Get http://gateway.openfaas:8080/system/info: dial tcp 10.43.223.78:8080: connect: connection refused

goroutine 1 [running]:
main.main()
	/go/src/github.com/openfaas-incubator/faas-idler/main.go:72 +0x847
```

```
kubectl logs -n openfaas gateway-5cffc9c5bd-zw87k gateway
2020/05/24 16:25:35 HTTP Read Timeout: 1m5s
2020/05/24 16:25:35 HTTP Write Timeout: 1m5s
2020/05/24 16:25:35 Binding to external function provider: http://127.0.0.1:8081/
2020/05/24 16:25:35 Async enabled: Using NATS Streaming.
2020/05/24 16:25:35 Opening connection to nats://nats.openfaas.svc.cluster.local:4222
2020/05/24 16:25:35 Connect: nats://nats.openfaas.svc.cluster.local:4222
&{0xc00000dd00}
2020/05/24 16:25:35 nats: no servers available for connection
```
```
kubectl logs -n openfaas gateway-5cffc9c5bd-zw87k faas-netes          
W0524 16:04:29.406415       1 client_config.go:543] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
2020/05/24 16:04:29 HTTP Read Timeout: 1m0s
2020/05/24 16:04:29 HTTP Write Timeout: 1m0s
2020/05/24 16:04:29 HTTPProbe: true
2020/05/24 16:04:29 SetNonRootUser: false
2020/05/24 16:04:29 Starting operator. Version: 0.10.5	commit: 9be50543b372381a505e9e54a1356bb076c8f01f
```
## Next steps

You may [join Slack](https://docs.openfaas.com/community) for community support.

**Comment by pixeldrew** [comment]
How is this an esoteric combination? It's a very basic and common k3s setup. I've tried in both amd64 (VirtualBox) and aarch64 on an RPI4. Rancher are pushing k3os as their starting point for k3s and if openfaas doesn't work I could see people deploying kubeless or one of the many other faas frameworks.

Using k3d I was able to at least run a test deployment. I've been comparing the logs of both and can't find anything different except for the hex line right after the connect log in the gateway pod.
```
2020/05/24 16:25:35 Connect: nats://nats.openfaas.svc.cluster.local:4222
&{0xc00000dd00}
```
Then in the logs of the nats pod on the working k3d cluster there is this:
```
STREAM: Channel "faas-request" has been created
```
Whereas this line never appears in the k3os nats pod. 

It'd be really helpful if you could provide something to help debug.

**Comment by pixeldrew** [comment]
I've ran:

```sh
kubectl run -n openfaas -it --rm --restart=Never nc \                                                                                                                                                                                                        
--image=quay.io/stefanprodan/podinfo:0.2.1 \
--image-pull-policy=Always \
-- sh
If you don't see a command prompt, try pressing enter.
/ # nc -v nats.openfaas.svc.cluster.local. 4222
nats.openfaas.svc.cluster.local. (10.43.138.217:4222) open
INFO {"server_id":"NC24ATRAOLS7E5JDIJTR3UFKWSVASEFUIMEXQS7BT2GUSWZKXWR3IBWI","server_name":"NC24ATRAOLS7E5JDIJTR3UFKWSVASEFUIMEXQS7BT2GUSWZKXWR3IBWI","version":"2.1.4","proto":1,"git_commit":"fb009af","go":"go1.13.7","host":"0.0.0.0","port":4222,"max_payload":1048576,"client_id":4}
PING
```

So that rules out networking.

**Comment by alexellis** [comment]
I would encourage you to ask for help on the Rancher Slack. Since OpenFaaS works faultlessly with k3d and k3s, they should be able to help you to find whatever the delta is. Rancher are very helpful, and if you don't want to use Slack for some reason, you could open an issue on their GitHub repo, we have a good relationship between the communities.

Resorting to threats such as "if you don't help me, I'll just use framework X" is bad form, and is not going to get the response that you think it will. This is a community project run by volunteers, we're all in this together and folks who are collaborative receive better results. I hope that is fair by you?

I would echo what I earlier in my earlier comment, I think it would be a good next move for you to ask in the Rancher Slack for help with k3os. If OpenFaaS works without fault with Kubeadm and KinD, then unfortunately I don't have time (unless it's for a customer) to debug k3os.

Alex

**Comment by alexellis** [comment]
Here's OpenFaaS with the latest helm chart coming up on k3d:

```bash
space-mini:~ alex$ k3d create
INFO[0000] Created cluster network with ID 00461e9ca7de0241ff95703212d93cb48b95d058b1bcb801a2a3af787a8405e2 
INFO[0000] Created docker volume  k3d-k3s-default-images 
INFO[0000] Creating cluster [k3s-default]               
INFO[0000] Creating server using docker.io/rancher/k3s:v1.17.3-k3s1... 
INFO[0000] SUCCESS: created cluster [k3s-default]       
INFO[0000] You can now use the cluster with:

export KUBECONFIG="$(k3d get-kubeconfig --name='k3s-default')"
kubectl cluster-info 
space-mini:~ alex$ export KUBECONFIG="$(k3d get-kubeconfig --name='k3s-default')"
space-mini:~ alex$ kubectl get nodes
NAME                     STATUS     ROLES    AGE   VERSION
k3d-k3s-default-server   NotReady   master   5s    v1.17.3+k3s1
space-mini:~ alex$ kubectl get nodes -w
NAME                     STATUS     ROLES    AGE   VERSION
k3d-k3s-default-server   NotReady   master   8s    v1.17.3+k3s1
k3d-k3s-default-server   Ready      master   10s   v1.17.3+k3s1
k3d-k3s-default-server   Ready      master   11s   v1.17.3+k3s1
k3d-k3s-default-server   Ready      master   11s   v1.17.3+k3s1
k3d-k3s-default-server   Ready      master   11s   v1.17.3+k3s1
k3d-k3s-default-server   Ready      master   12s   v1.17.3+k3s1
^Cspace-mini:~ alexarkade install openfaas
Using kubeconfig: /Users/alex/.config/k3d/k3s-default/kubeconfig.yaml
Using helm3
Node architecture: "amd64"
Client: "x86_64", "Darwin"
2020/05/26 15:25:02 User dir established as: /Users/alex/.arkade/
"openfaas" has been added to your repositories
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "traefik" chart repository
...Successfully got an update from the "fluxcd" chart repository
...Successfully got an update from the "jetstack" chart repository
...Successfully got an update from the "inlets" chart repository
...Successfully got an update from the "expressjs-k8s" chart repository
...Successfully got an update from the "openfaas" chart repository
...Successfully got an update from the "crossplane-alpha" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈ Happy Helming!⎈ 
VALUES values.yaml
Command: /Users/alex/.arkade/bin/helm3/helm [upgrade --install openfaas openfaas/openfaas --namespace openfaas --values /var/folders/p7/ptxtv_pd3n12fd6mc5wjhk1h0000gn/T/charts/openfaas/values.yaml --set ingressOperator.create=false --set serviceType=NodePort --set gateway.directFunctions=true --set faasnetes.imagePullPolicy=Always --set openfaasImagePullPolicy=IfNotPresent --set basicAuthPlugin.replicas=1 --set gateway.replicas=1 --set queueWorker.replicas=1 --set queueWorker.maxInflight=1 --set basic_auth=true --set clusterRole=false --set operator.create=false]
Release "openfaas" does not exist. Installing it now.
NAME: openfaas
LAST DEPLOYED: Tue May 26 15:25:11 2020
NAMESPACE: openfaas
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
To verify that openfaas has started, run:

  kubectl -n openfaas get deployments -l "release=openfaas, app=openfaas"
=======================================================================
= OpenFaaS has been installed.                                        =
=======================================================================

# Get the faas-cli
curl -SLsf https://cli.openfaas.com | sudo sh

# Forward the gateway to your machine
kubectl rollout status -n openfaas deploy/gateway
kubectl port-forward -n openfaas svc/gateway 8080:8080 &

# If basic auth is enabled, you can now log into your gateway:
PASSWORD=$(kubectl get secret -n openfaas basic-auth -o jsonpath="{.data.basic-auth-password}" | base64 --decode; echo)
echo -n $PASSWORD | faas-cli login --username admin --password-stdin

faas-cli store deploy figlet
faas-cli list

# For Raspberry Pi
faas-cli store list \
 --platform armhf

faas-cli store deploy figlet \
 --platform armhf

# Find out more at:
# https://github.com/openfaas/faas

Thanks for using arkade!
space-mini:~ alex$ kubectl get deploy -n openfaas -w
NAME                READY   UP-TO-DATE   AVAILABLE   AGE
faas-idler          0/1     1            0           10s
prometheus          0/1     1            0           10s
queue-worker        0/1     1            0           10s
alertmanager        0/1     1            0           10s
nats                0/1     1            0           10s
basic-auth-plugin   0/1     1            0           10s
gateway             0/1     1            0           10s
faas-idler          1/1     1            1           10s
basic-auth-plugin   1/1     1            1           11s
nats                1/1     1            1           11s
queue-worker        1/1     1            1           11s
alertmanager        1/1     1            1           14s
faas-idler          0/1     1            0           16s
gateway             1/1     1            1           17s
faas-idler          1/1     1            1           17s
^Cspace-mini:~ alex$ 
space-mini:~ alex$ 
space-mini:~ alex$ kubectl get deploy -n openfaas -w
NAME                READY   UP-TO-DATE   AVAILABLE   AGE
prometheus          0/1     1            0           25s
basic-auth-plugin   1/1     1            1           25s
nats                1/1     1            1           25s
queue-worker        1/1     1            1           25s
alertmanager        1/1     1            1           25s
gateway             1/1     1            1           25s
faas-idler          1/1     1            1           25s
prometheus          1/1     1            1           26s
^Cspace-mini:~ alex$ 
space-mini:~ alex$ 
space-mini:~ alex$ kubectl get deploy -n openfaas -w
NAME                READY   UP-TO-DATE   AVAILABLE   AGE
basic-auth-plugin   1/1     1            1           29s
nats                1/1     1            1           29s
queue-worker        1/1     1            1           29s
alertmanager        1/1     1            1           29s
gateway             1/1     1            1           29s
faas-idler          1/1     1            1           29s
prometheus          1/1     1            1           29s
```

**Comment by pixeldrew** [comment]
Like I said, I was able to get it running in k3d.

Was not a threat, Kubeless works on k3os, so I'll go with that.

**Comment by alexellis** [comment]
/set title: Support issue for k3os and VirtualBox

**Comment by Waterdrips** [comment]
/lock: looks like everythingf installed ok using k3d. 

If you need any detailed support the best place is the OpenFaaS Slack lots more people will see the messages and may have had a similar experience.
